name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          sleep 60
          echo "Code coverage is 90%"

      - name: Lint code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: |
          echo "Building the site..."
          # Replace the following command with the build command for your project
          # For example, npm run build or yarn build
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
          user_name: vivekvag281
          user_email: vivekvag281@gmail.com
